return {
  -- {
  --   'lukas-reineke/indent-blankline.nvim',
  --   enabled = true,
  --   event = 'lazyfile',
  --   opts = {
  --     indent = {
  --       char = ' ',
  --       tab_char = ' ',
  --     },
  --     scope = { show_start = false, show_end = false },
  --     exclude = {
  --       filetypes = {
  --         'help',
  --         'alpha',
  --         'dashboard',
  --         'neo-tree',
  --         'trouble',
  --         'trouble',
  --         'lazy',
  --         'mason',
  --         'notify',
  --         'toggleterm',
  --         'lazyterm',
  --       },
  --     },
  --   },
  --   main = 'ibl',
  -- },
}
